version: "3.7"
services:
  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 3309:3306
